# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuffID', models.CharField(max_length=20)),
                ('StuddName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SecurityID', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('IDcard', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=20)),
                ('Gender', models.IntegerField()),
                ('Address', models.CharField(max_length=20)),
                ('Career', models.CharField(max_length=20)),
                ('Education', models.CharField(max_length=20)),
                ('Company', models.CharField(max_length=20)),
                ('IsFreeze', models.IntegerField()),
                ('AccountID', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Balance', models.FloatField(max_length=80)),
                ('LoginPasswd', models.CharField(max_length=20)),
                ('BuyPassword', models.CharField(max_length=20)),
            ],
        ),
    ]
