# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountID', models.CharField(max_length=20)),
                ('ActiveMoney', models.FloatField()),
                ('FrozenMoney', models.FloatField()),
                ('BankCard', models.CharField(max_length=20)),
            ],
        ),
    ]
