# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='database.UserTable')),
                ('StockID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='database.StockInfo')),
            ],
        ),
    ]
