# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_capitalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityStockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SecurityID', models.CharField(max_length=20)),
                ('StockID', models.CharField(max_length=20)),
                ('ShareHolding', models.IntegerField()),
                ('status', models.IntegerField()),
                ('BuyPrice', models.FloatField()),
            ],
        ),
    ]
