# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_securitystockinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstNotDealed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstID', models.CharField(max_length=20)),
                ('TimeSubmit', models.DateTimeField()),
                ('TimeOutOfDate', models.DateTimeField()),
                ('InstType', models.IntegerField()),
                ('InstState', models.IntegerField()),
                ('StockID', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('PriceSubmit', models.FloatField()),
                ('AccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.CapitalAccountInfo')),
                ('SecurityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.SecurityAccountInfo')),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockName', models.TextField()),
                ('StockID', models.CharField(max_length=20)),
                ('CurrentPrice', models.FloatField()),
                ('MaxPrice', models.FloatField()),
                ('MinPrice', models.FloatField()),
                ('TodayOpeningPrice', models.FloatField()),
                ('YesterdayClosingPrice', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('UpLimit', models.FloatField()),
                ('BottomLimit', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='instoutofdate',
            name='AccountID',
        ),
        migrations.RemoveField(
            model_name='instoutofdate',
            name='SecurityID',
        ),
        migrations.DeleteModel(
            name='InstOutOfDate',
        ),
    ]
