# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20160604_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='MailAddr',
            field=models.CharField(max_length=30),
        ),
    ]
