# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockID', models.CharField(max_length=30)),
                ('StockName', models.CharField(max_length=30)),
                ('CurrentPrice', models.FloatField()),
                ('A_D', models.FloatField()),
                ('UpLimit', models.FloatField()),
                ('DownLimit', models.FloatField()),
            ],
        ),
    ]
